-   id: gha-workflow-shellcheck
    name: GitHub Actions workflow shellcheck
    description: Runs shellcheck on GitHub Actions workflow steps
    entry: gha-workflow-shellcheck
    language: python
    types: [yaml]
